language: php
dist: trusty
php:
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

env:
  matrix:
    - SYMFONY_VERSION=3.2.*
  global:
    - SYMFONY_PHPUNIT_DIR=.phpunit
    - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - SYMFONY_PHPUNIT_VERSION=5.7

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.3.* STABILITY=dev
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - ${STABILITY:+ composer config 'minimum-stability' "$STABILITY"}
  - ${SYMFONY_VERSION:+ composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update}

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script: vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
